FROM golang:1.25-alpine AS build

ENV GOPROXY=https://mirrors.aliyun.com/goproxy/

# RUN apk --no-cache add ca-certificates tzdata

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/aurora-agent .

FROM alpine:3.22

RUN apk --no-cache add tzdata

WORKDIR /app

COPY --from=build /out/aurora-agent /app/aurora-agent

RUN mkdir -p /app/conf /app/log

EXPOSE 1119

CMD ["/app/aurora-agent"]
